#  ლოგიკური ოპერატორებისა და შედარების ოპერატორებზე შეადგინეთ 10 მაგალითი,5 მაგალითმა უნდა დააბრუნოს False და 5 მაგალითმა უნდა დაააბრუნოს True
print("false"  and "true") 
print("false" and "true")
print("true" or "true")
print("false" and "true") 
print("false"  or "true") 
print("false" or "true")
print("true" or "true")
print("false" or "true") 
# 3) კომენტარის სახით დაწერეთ თუ რა არის sequancing,iteration,selection აღწერე თითეული მათგანი თქვენი სიტყვებით
#sequancing nakadis gayola
#iteration pirobis gameoreba sanam ar sesruldeba
#selection arcevani pirobis mixedvit
# 4) მოიყვანე sequencing ის მაგალითი,და კომენტარით მიუწერე რატომ არის შენს მიერ მოყვანილი მაგალითი sequence
print(10)
#miyveba cems brzanebas aka nakads
print()

# 5) კომენტარის სახით ახსენით თუ რა არის for loop და რაში გვეხმარება ის
#for loop aris funqcia romelic sasualebas gvazlevs gavamartivot magalitad meti commandebis daprintvasi

# 6) კომენტარის სახით ახსენით თუ რა გადაეცემა range() ფუნქციას და როგორ მუშაობს for loop
#range funqcia aris sadac gadaewodeba ramdeni unda gaaketos esa tu is operacia

# 7) შენი დავალებაა ტერმინალში გამოიყანო საყვარელი ავტომობილის სახელი ტერმინალში გამოიყენე for loop
for i in range(1):
    print("toyota supra mk4")
# 8) შენი დავალებაა ტერმინალში გამოიტანო შენი გვარი 100 ჯერ
for i in range(100):
    print("barbakadze")

# 9) შენი დავალებაა ტერმინალში გამოიტანო საყვარელი ფერი 46 ჯერ
for i in range(42):
    print("green")

# 10) შენი დავალებაა ტერმინალში გამოიტანო შენი სახელის პირველი ასო 32 ჯერ
for i in range(32):
    print("g")


# # გამეორება / Revise -->

# 11) მომხმარებელს შემოატანინე 3 სტრინგ ტიპის და ერთი ინტეჯერ ტიპის მნიშვნელობები და შენი დავალებაა მოახდინო ამ ოთხი მნიშვნელობის კონკატინაცია(გამოიყენე შესაბამისი ფუნქცია რომ მოახდინოთ მონაცემთა ტიპიების გარდაქმნა ერთ მონაცემთა ტიპში რომ შეძლოთ კონკატინაცია)
# a = input(str("enter ur num"))
# b = input(str("enter ur num"))

# c = input(str("enter ur num"))
# d = input(str("enter ur num"))
# 12) შექმენი 4 ცვლადი,თითოეულში შეინახე განსხვავებული მონაცემთა ტიპები,შენი დავალებაა გაიგო ამ ცვლადებში შენახული მნიშვნელობის მონაცემთა ტიპი(გამოიყენე შესაბამისი ფუნქცია)
# a = "5"
# c = "1"
# d = "a"
# print(type(a , b , c))
# print(type(d))
# 13) მომხმარებელს შემოატანინე 4 რიცხვი და ტერმინალში დააბრუნე ამ 4 რიცხვის ჯამი
a = input(int(1))
b = input(int(2))
c = input(int(3))
d = input(int(4))

print(a + b + c + d)




